name: the_hitters_ledger
description: Baseball mental performance app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.1.0
  intl: ^0.18.1
  audioplayers: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# This section defines your App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21

# This section defines your Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash.png"
  android_12:
    image: "assets/splash.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  # Ensures the app knows to look in your assets folder
  assets:
    - assets/
